package com.vitalii.komaniak.domain.model.content_compiler

import com.vitalii.komaniak.domain.model.content_compiler.Badge

data class Text(
    val title: String?,
    val showTitle: String?,
    val titleImage: String?,
    val subtitle: String?,
    val seasonEpisodeNumber: String?,
    val episodeTitle: String?,
    val description: String?,
    val videoNickname: String?,
    val originalAirDate: String?,
    val airingTime: String?,
    val startDate: String?,
    val endDate: String?,
    val airing: String?,
    val startTime: String?,
    val endTime: String?,
    val badge: Badge?,
    val logicalCTA: String?,
    val header: String?,
    val link: String?,
    val qrCode: String?,
    val qrCodeHint: String?,
    val flag: String?,
    val subhead: String?,
    val tvContentRating: String?,
    val runtime: String?,
    val availabilityMessage: String?,
    val genre: String?,
    val subheading: List<Badge>?,
    val secondarySubheading: List<Badge>?,
    val topLeftBadge: Badge?,
    val bottomLeftBadge: Badge?,
    val bottomRightBadge: Badge?,
    val bottomDescription: String?,
    val minimizedPlayerTitle: String?,
    val minimizedPlayerSubtitle: String?,
)